// < This file will be generated by vs //

using Demo.Sealed;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo.Partial
{
    abstract internal partial class Employee : Parent
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public  int? Age { get; set; }

        // Partial Method
        /// if i need to use this method but it still not implemted so will make it partial
        /// and use it
        
        partial void DoSomeCode();
        public void Test()
        {
            /*Console.WriteLine(*/
            DoSomeCode();/*);*/
        }

        // What the constrent to use it if still NOT IMPLEMENTED?
        /// 1. should not give Access Modifire
        /// 2. Return void
        /// 3. Dosn't take Parameters


    }
}
